MACRO(SET_FLEX_FILE _sourceFile _targetFile)

ADD_CUSTOM_COMMAND(OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/${_targetFile}
		   COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/../contrib/bin/${ARCH}/flex.exe
		   ARGS -o${CMAKE_CURRENT_BINARY_DIR}/${_targetFile} ${CMAKE_CURRENT_SOURCE_DIR}/${_sourceFile}
		   MAIN_DEPENDENCY ${CMAKE_CURRENT_SOURCE_DIR}/${_sourceFile})

ENDMACRO(SET_FLEX_FILE)
