#
# Find the RTFACTREMOTE includes and library
##
# sets RTFACTREMOTE_INCLUDE_DIR
#      RTFACTREMOTE_LIBRARY
#      RTFACTREMOTE_DEBUG_LIBRARY
#      RTFACTREMOTE_FOUND
#      RTFACTREMOTE_LIBRARIES
#      RTFACTREMOTE_LIBRARY_DIR

FIND_PATH(RTFACTREMOTE_INCLUDE_DIR RTremote/Renderer.hpp
  ${RTFACTREMOTE_ROOT}/include
  /usr/local/include
  /usr/include
)


IF(WIN32)
  FIND_LIBRARY(RTFACTREMOTE_LIBRARY
               NAMES RTfactRemote
               PATHS ${RTFACTREMOTE_INCLUDE_DIR}/../lib
               ${RTFACTREMOTE_INCLUDE_DIR}/../lib/${ARCH})
  FIND_LIBRARY(RTFACTREMOTE_LIBRARY_DEBUG
               NAMES RTfactRemote_debug RTfactRemoted RTfactRemote
               PATHS ${RTFACTREMOTE_INCLUDE_DIR}/../lib
               ${RTFACTREMOTE_INCLUDE_DIR}/../lib/${ARCH})
ELSE(WIN32)
  FIND_LIBRARY(RTFACTREMOTE_LIBRARY
  	       NAMES RTfactRemote
               PATHS ${RTFACTREMOTE_INCLUDE_DIR}/../lib
               /usr/local/lib
               /usr/lib)
  FIND_LIBRARY(RTFACTREMOTE_LIBRARY_DEBUG 
  	       NAMES RTfactRemote_debug RTfactRemoted RTfactRemote
               PATHS ${RTFACTREMOTE_INCLUDE_DIR}/../lib
               /usr/local/lib
               /usr/lib)
ENDIF(WIN32)


SET(RTFACTREMOTE_FOUND "NO")
IF(RTFACTREMOTE_INCLUDE_DIR AND RTFACTREMOTE_LIBRARY)
  GET_FILENAME_COMPONENT( RTFACTREMOTE_LIBRARY_DIR ${RTFACTREMOTE_LIBRARY} PATH )
  GET_FILENAME_COMPONENT( RTFACTREMOTE_LIBRARY_NAME ${RTFACTREMOTE_LIBRARY} NAME )
  IF(WIN32)
    SET(RTFACTREMOTE_LIBRARIES optimized ${RTFACTREMOTE_LIBRARY_NAME})
    IF(RTFACTREMOTE_LIBRARY_DEBUG)
      GET_FILENAME_COMPONENT( RTFACTREMOTE_LIBRARY_DIR_DEBUG ${RTFACTREMOTE_LIBRARY_DEBUG} PATH )
      GET_FILENAME_COMPONENT( RTFACTREMOTE_LIBRARY_NAME_DEBUG ${RTFACTREMOTE_LIBRARY_DEBUG} NAME )      
      SET(RTFACTREMOTE_LIBRARIES ${RTFACTREMOTE_LIBRARIES} debug ${RTFACTREMOTE_LIBRARY_NAME_DEBUG})
    ENDIF(RTFACTREMOTE_LIBRARY_DEBUG)
  ELSE(WIN32)
    SET(RTFACTREMOTE_LIBRARIES general ${RTFACTREMOTE_LIBRARY_NAME})
  ENDIF(WIN32)
  SET(RTFACTREMOTE_FOUND "YES")
ENDIF(RTFACTREMOTE_INCLUDE_DIR AND RTFACTREMOTE_LIBRARY)

SET(RTFACTREMOTE_LIBRARIES "${RTFACTREMOTE_LIBRARIES}" CACHE STRING "List of RTFACTREMOTE libraries")
SET(RTFACTREMOTE_LIBRARY_DIRS "${RTFACTREMOTE_LIBRARY_DIR}" "${RTFACTREMOTE_LIBRARY_DIR_DEBUG}" CACHE STRING "Path to RTfactRemote libraries")