# parts taken from FindSceniX.cmake


# If PhysX SDK home is not set, we cannot find PhysX
if("$ENV{PHYSXHOME}" STREQUAL "" )
	SET(PHYSX_FOUND "NO")
	SET(PHYSX_INCLUDE_DIR "NOTFOUND")
	SET(PHYSX_LIBRARIES "NOTFOUND")
	
	# Die hard, if PhysX was required, otherwise only warn
	if(PhysX_FIND_REQUIRED)
		MESSAGE(SEND_ERROR "PhysX NOT FOUND ($PHYSXHOME==''), is it properly installed?") 
	else(PhysX_FIND_REQUIRED)
		MESSAGE("PhysX NOT FOUND ($PHYSXHOME==''), is it properly installed?") 
	endif(PhysX_FIND_REQUIRED)
	return()
endif( "$ENV{PHYSXHOME}" STREQUAL "" )

if ( "${PHYSX_HOME}" STREQUAL "" )
  file(TO_CMAKE_PATH $ENV{PHYSXHOME} PHYSX_HOME_TMP)
  set( PHYSX_HOME ${PHYSX_HOME_TMP} CACHE PATH "PhysX SDK directory" )
endif()

if(WIN32)
	if( CMAKE_SIZEOF_VOID_P EQUAL 8 )
	  set ( PHYSX_ARCH "win64" )
	  set ( PHYSX_FILE_ENDING "64" )
	else ()
	  set ( PHYSX_ARCH "win32" )
	  set ( PHYSX_FILE_ENDING "" )
	endif()
ENDIF(WIN32)

IF(WIN32)
	SET(PX_INC	"${PHYSX_HOME}/SDKs")
	SET(PHYSX_NXCOOKING_LIBRARY "${PHYSX_HOME}/SDKs/lib/${PHYSX_ARCH}/PhysXCooking${PHYSX_FILE_ENDING}.lib")
	SET(PHYSX_NXCHARACTER_LIBRARY "${PHYSX_HOME}/SDKs/lib/${PHYSX_ARCH}/NxCharacter${PHYSX_FILE_ENDING}.lib")
	SET(PHYSX_PHYSXLOADER_LIBRARY "${PHYSX_HOME}/SDKs/lib/${PHYSX_ARCH}/PhysXLoader${PHYSX_FILE_ENDING}.lib")
	SET(PHYSX_PHYSXCORE_LIBRARY "${PHYSX_HOME}/SDKs/lib/${PHYSX_ARCH}/PhysXCore${PHYSX_FILE_ENDING}.lib")
	SET(PHYSX_LIBRARIES ${PHYSX_NXCOOKING_LIBRARY} ${PHYSX_NXCHARACTER_LIBRARY} ${PHYSX_PHYSXLOADER_LIBRARY} ${PHYSX_PHYSXCORE_LIBRARY} )
	SET(PHYSX_FOUND	"YES")
ENDIF(WIN32)

# TODO: test Unix version!
IF(UNIX)
	SET(PX_INC	"${PHYSX_HOME}/SDKs")
	SET(PHYSX_NXCOOKING_LIBRARY "${PHYSX_HOME}/libNxCooking.so")
	SET(PHYSX_NXCHARACTER_LIBRARY "${PHYSX_HOME}/libNxCharacter.so")
	SET(PHYSX_PHYSXLOADER_LIBRARY "${PHYSX_HOME}/libPhysXLoader.so")
	SET(PHYSX_PHYSXCORE_LIBRARY "${PHYSX_HOME}/libPhysXCore.so")
	SET(PHYSX_LIBRARIES ${PHYSX_NXCOOKING_LIBRARY} ${PHYSX_NXCHARACTER_LIBRARY} ${PHYSX_PHYSXLOADER_LIBRARY} ${PHYSX_PHYSXCORE_LIBRARY})
	SET(PHYSX_FOUND "YES")
ENDIF(UNIX)

IF(PHYSX_FOUND)
	SET(PHYSX_INCLUDE_DIRS ${PX_INC} "${PX_INC}/Physics/include" "${PX_INC}/Foundation/include" "${PX_INC}/Cooking/include" "${PX_INC}/NxCharacter/include" "${PX_INC}/PhysXLoader/include")
	if(UNIX)
		set(CMAKE_CXX_FLAGS "-DLINUX -DPHYSX")
	endif(UNIX)
	message("nVidia PhysX found")
ENDIF(PHYSX_FOUND)
